// Generated by jextract

package com.loadingbyte.cinecred.natives.clib;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class clib_h extends clib_h$shared {

    clib_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class cpuid {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            clib_h.C_INT,
            clib_h.C_INT,
            clib_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("cpuid");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void cpuid(unsigned int leaf, unsigned int subleaf, unsigned int *registers)
     * }
     */
    public static FunctionDescriptor cpuid$descriptor() {
        return cpuid.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void cpuid(unsigned int leaf, unsigned int subleaf, unsigned int *registers)
     * }
     */
    public static MethodHandle cpuid$handle() {
        return cpuid.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void cpuid(unsigned int leaf, unsigned int subleaf, unsigned int *registers)
     * }
     */
    public static MemorySegment cpuid$address() {
        return cpuid.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void cpuid(unsigned int leaf, unsigned int subleaf, unsigned int *registers)
     * }
     */
    public static void cpuid(int leaf, int subleaf, MemorySegment registers) {
        var mh$ = cpuid.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cpuid", leaf, subleaf, registers);
            }
            mh$.invokeExact(leaf, subleaf, registers);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

