// Generated by jextract

package com.loadingbyte.cinecred.natives.nfd;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct {
 *     void* ptr;
 * };
 * }
 */
public class nfdpathsetenum_t {

    public static MemoryLayout $LAYOUT() {
        return constants$0.const$2;
    }
    public static VarHandle ptr$VH() {
        return constants$0.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * void* ptr;
     * }
     */
    public static MemorySegment ptr$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$0.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * void* ptr;
     * }
     */
    public static void ptr$set(MemorySegment seg, MemorySegment x) {
        constants$0.const$3.set(seg, x);
    }
    public static MemorySegment ptr$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$0.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void ptr$set(MemorySegment seg, long index, MemorySegment x) {
        constants$0.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena arena) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, arena); }
}


