// Generated by jextract

package com.loadingbyte.cinecred.natives.decklinkcapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void (*deviceNotificationCallback_t)(void* device);
 * }
 */
public interface deviceNotificationCallback_t {

    void apply(java.lang.foreign.MemorySegment device);
    static MemorySegment allocate(deviceNotificationCallback_t fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$0.const$1, fi, constants$0.const$0, scope);
    }
    static deviceNotificationCallback_t ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (java.lang.foreign.MemorySegment _device) -> {
            try {
                constants$0.const$2.invokeExact(symbol, _device);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


