// Generated by jextract

package com.loadingbyte.cinecred.natives.zimg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class zimg_h extends zimg_h$shared {

    zimg_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class zimg_get_last_error {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            zimg_h.C_INT,
            zimg_h.C_POINTER,
            zimg_h.C_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("zimg_get_last_error");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_get_last_error(char *err_msg, size_t n)
     * }
     */
    public static FunctionDescriptor zimg_get_last_error$descriptor() {
        return zimg_get_last_error.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_get_last_error(char *err_msg, size_t n)
     * }
     */
    public static MethodHandle zimg_get_last_error$handle() {
        return zimg_get_last_error.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_get_last_error(char *err_msg, size_t n)
     * }
     */
    public static MemorySegment zimg_get_last_error$address() {
        return zimg_get_last_error.ADDR;
    }

    /**
     * {@snippet lang=c :
     * zimg_error_code_e zimg_get_last_error(char *err_msg, size_t n)
     * }
     */
    public static int zimg_get_last_error(MemorySegment err_msg, long n) {
        var mh$ = zimg_get_last_error.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("zimg_get_last_error", err_msg, n);
            }
            return (int)mh$.invokeExact(err_msg, n);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int ZIMG_CPU_AUTO_64B = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_cpu_type_e.ZIMG_CPU_AUTO_64B = 2
     * }
     */
    public static int ZIMG_CPU_AUTO_64B() {
        return ZIMG_CPU_AUTO_64B;
    }
    private static final int ZIMG_PIXEL_BYTE = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_pixel_type_e.ZIMG_PIXEL_BYTE = 0
     * }
     */
    public static int ZIMG_PIXEL_BYTE() {
        return ZIMG_PIXEL_BYTE;
    }
    private static final int ZIMG_PIXEL_WORD = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_pixel_type_e.ZIMG_PIXEL_WORD = 1
     * }
     */
    public static int ZIMG_PIXEL_WORD() {
        return ZIMG_PIXEL_WORD;
    }
    private static final int ZIMG_PIXEL_HALF = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_pixel_type_e.ZIMG_PIXEL_HALF = 2
     * }
     */
    public static int ZIMG_PIXEL_HALF() {
        return ZIMG_PIXEL_HALF;
    }
    private static final int ZIMG_PIXEL_FLOAT = (int)3L;
    /**
     * {@snippet lang=c :
     * enum zimg_pixel_type_e.ZIMG_PIXEL_FLOAT = 3
     * }
     */
    public static int ZIMG_PIXEL_FLOAT() {
        return ZIMG_PIXEL_FLOAT;
    }
    private static final int ZIMG_RANGE_LIMITED = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_pixel_range_e.ZIMG_RANGE_LIMITED = 0
     * }
     */
    public static int ZIMG_RANGE_LIMITED() {
        return ZIMG_RANGE_LIMITED;
    }
    private static final int ZIMG_RANGE_FULL = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_pixel_range_e.ZIMG_RANGE_FULL = 1
     * }
     */
    public static int ZIMG_RANGE_FULL() {
        return ZIMG_RANGE_FULL;
    }
    private static final int ZIMG_COLOR_GREY = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_family_e.ZIMG_COLOR_GREY = 0
     * }
     */
    public static int ZIMG_COLOR_GREY() {
        return ZIMG_COLOR_GREY;
    }
    private static final int ZIMG_COLOR_RGB = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_family_e.ZIMG_COLOR_RGB = 1
     * }
     */
    public static int ZIMG_COLOR_RGB() {
        return ZIMG_COLOR_RGB;
    }
    private static final int ZIMG_COLOR_YUV = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_family_e.ZIMG_COLOR_YUV = 2
     * }
     */
    public static int ZIMG_COLOR_YUV() {
        return ZIMG_COLOR_YUV;
    }
    private static final int ZIMG_ALPHA_NONE = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_alpha_type_e.ZIMG_ALPHA_NONE = 0
     * }
     */
    public static int ZIMG_ALPHA_NONE() {
        return ZIMG_ALPHA_NONE;
    }
    private static final int ZIMG_FIELD_PROGRESSIVE = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_field_parity_e.ZIMG_FIELD_PROGRESSIVE = 0
     * }
     */
    public static int ZIMG_FIELD_PROGRESSIVE() {
        return ZIMG_FIELD_PROGRESSIVE;
    }
    private static final int ZIMG_FIELD_TOP = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_field_parity_e.ZIMG_FIELD_TOP = 1
     * }
     */
    public static int ZIMG_FIELD_TOP() {
        return ZIMG_FIELD_TOP;
    }
    private static final int ZIMG_FIELD_BOTTOM = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_field_parity_e.ZIMG_FIELD_BOTTOM = 2
     * }
     */
    public static int ZIMG_FIELD_BOTTOM() {
        return ZIMG_FIELD_BOTTOM;
    }
    private static final int ZIMG_CHROMA_LEFT = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_chroma_location_e.ZIMG_CHROMA_LEFT = 0
     * }
     */
    public static int ZIMG_CHROMA_LEFT() {
        return ZIMG_CHROMA_LEFT;
    }
    private static final int ZIMG_CHROMA_CENTER = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_chroma_location_e.ZIMG_CHROMA_CENTER = 1
     * }
     */
    public static int ZIMG_CHROMA_CENTER() {
        return ZIMG_CHROMA_CENTER;
    }
    private static final int ZIMG_CHROMA_TOP_LEFT = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_chroma_location_e.ZIMG_CHROMA_TOP_LEFT = 2
     * }
     */
    public static int ZIMG_CHROMA_TOP_LEFT() {
        return ZIMG_CHROMA_TOP_LEFT;
    }
    private static final int ZIMG_CHROMA_TOP = (int)3L;
    /**
     * {@snippet lang=c :
     * enum zimg_chroma_location_e.ZIMG_CHROMA_TOP = 3
     * }
     */
    public static int ZIMG_CHROMA_TOP() {
        return ZIMG_CHROMA_TOP;
    }
    private static final int ZIMG_CHROMA_BOTTOM_LEFT = (int)4L;
    /**
     * {@snippet lang=c :
     * enum zimg_chroma_location_e.ZIMG_CHROMA_BOTTOM_LEFT = 4
     * }
     */
    public static int ZIMG_CHROMA_BOTTOM_LEFT() {
        return ZIMG_CHROMA_BOTTOM_LEFT;
    }
    private static final int ZIMG_CHROMA_BOTTOM = (int)5L;
    /**
     * {@snippet lang=c :
     * enum zimg_chroma_location_e.ZIMG_CHROMA_BOTTOM = 5
     * }
     */
    public static int ZIMG_CHROMA_BOTTOM() {
        return ZIMG_CHROMA_BOTTOM;
    }
    private static final int ZIMG_MATRIX_RGB = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_RGB = 0
     * }
     */
    public static int ZIMG_MATRIX_RGB() {
        return ZIMG_MATRIX_RGB;
    }
    private static final int ZIMG_MATRIX_BT709 = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_BT709 = 1
     * }
     */
    public static int ZIMG_MATRIX_BT709() {
        return ZIMG_MATRIX_BT709;
    }
    private static final int ZIMG_MATRIX_UNSPECIFIED = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_UNSPECIFIED = 2
     * }
     */
    public static int ZIMG_MATRIX_UNSPECIFIED() {
        return ZIMG_MATRIX_UNSPECIFIED;
    }
    private static final int ZIMG_MATRIX_FCC = (int)4L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_FCC = 4
     * }
     */
    public static int ZIMG_MATRIX_FCC() {
        return ZIMG_MATRIX_FCC;
    }
    private static final int ZIMG_MATRIX_BT470_BG = (int)5L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_BT470_BG = 5
     * }
     */
    public static int ZIMG_MATRIX_BT470_BG() {
        return ZIMG_MATRIX_BT470_BG;
    }
    private static final int ZIMG_MATRIX_ST170_M = (int)6L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_ST170_M = 6
     * }
     */
    public static int ZIMG_MATRIX_ST170_M() {
        return ZIMG_MATRIX_ST170_M;
    }
    private static final int ZIMG_MATRIX_ST240_M = (int)7L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_ST240_M = 7
     * }
     */
    public static int ZIMG_MATRIX_ST240_M() {
        return ZIMG_MATRIX_ST240_M;
    }
    private static final int ZIMG_MATRIX_YCGCO = (int)8L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_YCGCO = 8
     * }
     */
    public static int ZIMG_MATRIX_YCGCO() {
        return ZIMG_MATRIX_YCGCO;
    }
    private static final int ZIMG_MATRIX_BT2020_NCL = (int)9L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_BT2020_NCL = 9
     * }
     */
    public static int ZIMG_MATRIX_BT2020_NCL() {
        return ZIMG_MATRIX_BT2020_NCL;
    }
    private static final int ZIMG_MATRIX_BT2020_CL = (int)10L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_BT2020_CL = 10
     * }
     */
    public static int ZIMG_MATRIX_BT2020_CL() {
        return ZIMG_MATRIX_BT2020_CL;
    }
    private static final int ZIMG_MATRIX_ST2085_YDZDX = (int)11L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_ST2085_YDZDX = 11
     * }
     */
    public static int ZIMG_MATRIX_ST2085_YDZDX() {
        return ZIMG_MATRIX_ST2085_YDZDX;
    }
    private static final int ZIMG_MATRIX_CHROMATICITY_DERIVED_NCL = (int)12L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_CHROMATICITY_DERIVED_NCL = 12
     * }
     */
    public static int ZIMG_MATRIX_CHROMATICITY_DERIVED_NCL() {
        return ZIMG_MATRIX_CHROMATICITY_DERIVED_NCL;
    }
    private static final int ZIMG_MATRIX_CHROMATICITY_DERIVED_CL = (int)13L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_CHROMATICITY_DERIVED_CL = 13
     * }
     */
    public static int ZIMG_MATRIX_CHROMATICITY_DERIVED_CL() {
        return ZIMG_MATRIX_CHROMATICITY_DERIVED_CL;
    }
    private static final int ZIMG_MATRIX_BT2100_ICTCP = (int)14L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_BT2100_ICTCP = 14
     * }
     */
    public static int ZIMG_MATRIX_BT2100_ICTCP() {
        return ZIMG_MATRIX_BT2100_ICTCP;
    }
    private static final int ZIMG_MATRIX_ST2128_IPT_C2 = (int)15L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_ST2128_IPT_C2 = 15
     * }
     */
    public static int ZIMG_MATRIX_ST2128_IPT_C2() {
        return ZIMG_MATRIX_ST2128_IPT_C2;
    }
    private static final int ZIMG_MATRIX_YCGCO_RE = (int)16L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_YCGCO_RE = 16
     * }
     */
    public static int ZIMG_MATRIX_YCGCO_RE() {
        return ZIMG_MATRIX_YCGCO_RE;
    }
    private static final int ZIMG_MATRIX_YCGCO_RO = (int)17L;
    /**
     * {@snippet lang=c :
     * enum zimg_matrix_coefficients_e.ZIMG_MATRIX_YCGCO_RO = 17
     * }
     */
    public static int ZIMG_MATRIX_YCGCO_RO() {
        return ZIMG_MATRIX_YCGCO_RO;
    }
    private static final int ZIMG_TRANSFER_BT709 = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_BT709 = 1
     * }
     */
    public static int ZIMG_TRANSFER_BT709() {
        return ZIMG_TRANSFER_BT709;
    }
    private static final int ZIMG_TRANSFER_UNSPECIFIED = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_UNSPECIFIED = 2
     * }
     */
    public static int ZIMG_TRANSFER_UNSPECIFIED() {
        return ZIMG_TRANSFER_UNSPECIFIED;
    }
    private static final int ZIMG_TRANSFER_BT470_M = (int)4L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_BT470_M = 4
     * }
     */
    public static int ZIMG_TRANSFER_BT470_M() {
        return ZIMG_TRANSFER_BT470_M;
    }
    private static final int ZIMG_TRANSFER_BT470_BG = (int)5L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_BT470_BG = 5
     * }
     */
    public static int ZIMG_TRANSFER_BT470_BG() {
        return ZIMG_TRANSFER_BT470_BG;
    }
    private static final int ZIMG_TRANSFER_BT601 = (int)6L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_BT601 = 6
     * }
     */
    public static int ZIMG_TRANSFER_BT601() {
        return ZIMG_TRANSFER_BT601;
    }
    private static final int ZIMG_TRANSFER_ST240_M = (int)7L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_ST240_M = 7
     * }
     */
    public static int ZIMG_TRANSFER_ST240_M() {
        return ZIMG_TRANSFER_ST240_M;
    }
    private static final int ZIMG_TRANSFER_LINEAR = (int)8L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_LINEAR = 8
     * }
     */
    public static int ZIMG_TRANSFER_LINEAR() {
        return ZIMG_TRANSFER_LINEAR;
    }
    private static final int ZIMG_TRANSFER_LOG_100 = (int)9L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_LOG_100 = 9
     * }
     */
    public static int ZIMG_TRANSFER_LOG_100() {
        return ZIMG_TRANSFER_LOG_100;
    }
    private static final int ZIMG_TRANSFER_LOG_316 = (int)10L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_LOG_316 = 10
     * }
     */
    public static int ZIMG_TRANSFER_LOG_316() {
        return ZIMG_TRANSFER_LOG_316;
    }
    private static final int ZIMG_TRANSFER_IEC_61966_2_4 = (int)11L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_IEC_61966_2_4 = 11
     * }
     */
    public static int ZIMG_TRANSFER_IEC_61966_2_4() {
        return ZIMG_TRANSFER_IEC_61966_2_4;
    }
    private static final int ZIMG_TRANSFER_BT1361 = (int)12L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_BT1361 = 12
     * }
     */
    public static int ZIMG_TRANSFER_BT1361() {
        return ZIMG_TRANSFER_BT1361;
    }
    private static final int ZIMG_TRANSFER_IEC_61966_2_1 = (int)13L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_IEC_61966_2_1 = 13
     * }
     */
    public static int ZIMG_TRANSFER_IEC_61966_2_1() {
        return ZIMG_TRANSFER_IEC_61966_2_1;
    }
    private static final int ZIMG_TRANSFER_BT2020_10 = (int)14L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_BT2020_10 = 14
     * }
     */
    public static int ZIMG_TRANSFER_BT2020_10() {
        return ZIMG_TRANSFER_BT2020_10;
    }
    private static final int ZIMG_TRANSFER_BT2020_12 = (int)15L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_BT2020_12 = 15
     * }
     */
    public static int ZIMG_TRANSFER_BT2020_12() {
        return ZIMG_TRANSFER_BT2020_12;
    }
    private static final int ZIMG_TRANSFER_ST2084 = (int)16L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_ST2084 = 16
     * }
     */
    public static int ZIMG_TRANSFER_ST2084() {
        return ZIMG_TRANSFER_ST2084;
    }
    private static final int ZIMG_TRANSFER_ST428 = (int)17L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_ST428 = 17
     * }
     */
    public static int ZIMG_TRANSFER_ST428() {
        return ZIMG_TRANSFER_ST428;
    }
    private static final int ZIMG_TRANSFER_ARIB_B67 = (int)18L;
    /**
     * {@snippet lang=c :
     * enum zimg_transfer_characteristics_e.ZIMG_TRANSFER_ARIB_B67 = 18
     * }
     */
    public static int ZIMG_TRANSFER_ARIB_B67() {
        return ZIMG_TRANSFER_ARIB_B67;
    }
    private static final int ZIMG_PRIMARIES_XYZ_D50 = (int)100L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_XYZ_D50 = 100
     * }
     */
    public static int ZIMG_PRIMARIES_XYZ_D50() {
        return ZIMG_PRIMARIES_XYZ_D50;
    }
    private static final int ZIMG_PRIMARIES_BT709 = (int)1L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_BT709 = 1
     * }
     */
    public static int ZIMG_PRIMARIES_BT709() {
        return ZIMG_PRIMARIES_BT709;
    }
    private static final int ZIMG_PRIMARIES_UNSPECIFIED = (int)2L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_UNSPECIFIED = 2
     * }
     */
    public static int ZIMG_PRIMARIES_UNSPECIFIED() {
        return ZIMG_PRIMARIES_UNSPECIFIED;
    }
    private static final int ZIMG_PRIMARIES_BT470_M = (int)4L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_BT470_M = 4
     * }
     */
    public static int ZIMG_PRIMARIES_BT470_M() {
        return ZIMG_PRIMARIES_BT470_M;
    }
    private static final int ZIMG_PRIMARIES_BT470_BG = (int)5L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_BT470_BG = 5
     * }
     */
    public static int ZIMG_PRIMARIES_BT470_BG() {
        return ZIMG_PRIMARIES_BT470_BG;
    }
    private static final int ZIMG_PRIMARIES_ST170_M = (int)6L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_ST170_M = 6
     * }
     */
    public static int ZIMG_PRIMARIES_ST170_M() {
        return ZIMG_PRIMARIES_ST170_M;
    }
    private static final int ZIMG_PRIMARIES_ST240_M = (int)7L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_ST240_M = 7
     * }
     */
    public static int ZIMG_PRIMARIES_ST240_M() {
        return ZIMG_PRIMARIES_ST240_M;
    }
    private static final int ZIMG_PRIMARIES_FILM = (int)8L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_FILM = 8
     * }
     */
    public static int ZIMG_PRIMARIES_FILM() {
        return ZIMG_PRIMARIES_FILM;
    }
    private static final int ZIMG_PRIMARIES_BT2020 = (int)9L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_BT2020 = 9
     * }
     */
    public static int ZIMG_PRIMARIES_BT2020() {
        return ZIMG_PRIMARIES_BT2020;
    }
    private static final int ZIMG_PRIMARIES_ST428 = (int)10L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_ST428 = 10
     * }
     */
    public static int ZIMG_PRIMARIES_ST428() {
        return ZIMG_PRIMARIES_ST428;
    }
    private static final int ZIMG_PRIMARIES_ST431_2 = (int)11L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_ST431_2 = 11
     * }
     */
    public static int ZIMG_PRIMARIES_ST431_2() {
        return ZIMG_PRIMARIES_ST431_2;
    }
    private static final int ZIMG_PRIMARIES_ST432_1 = (int)12L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_ST432_1 = 12
     * }
     */
    public static int ZIMG_PRIMARIES_ST432_1() {
        return ZIMG_PRIMARIES_ST432_1;
    }
    private static final int ZIMG_PRIMARIES_EBU3213_E = (int)22L;
    /**
     * {@snippet lang=c :
     * enum zimg_color_primaries_e.ZIMG_PRIMARIES_EBU3213_E = 22
     * }
     */
    public static int ZIMG_PRIMARIES_EBU3213_E() {
        return ZIMG_PRIMARIES_EBU3213_E;
    }
    private static final int ZIMG_RESIZE_POINT = (int)0L;
    /**
     * {@snippet lang=c :
     * enum zimg_resample_filter_e.ZIMG_RESIZE_POINT = 0
     * }
     */
    public static int ZIMG_RESIZE_POINT() {
        return ZIMG_RESIZE_POINT;
    }
    private static final int ZIMG_RESIZE_LANCZOS = (int)5L;
    /**
     * {@snippet lang=c :
     * enum zimg_resample_filter_e.ZIMG_RESIZE_LANCZOS = 5
     * }
     */
    public static int ZIMG_RESIZE_LANCZOS() {
        return ZIMG_RESIZE_LANCZOS;
    }

    private static class zimg_filter_graph_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            zimg_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("zimg_filter_graph_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void zimg_filter_graph_free(zimg_filter_graph *ptr)
     * }
     */
    public static FunctionDescriptor zimg_filter_graph_free$descriptor() {
        return zimg_filter_graph_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void zimg_filter_graph_free(zimg_filter_graph *ptr)
     * }
     */
    public static MethodHandle zimg_filter_graph_free$handle() {
        return zimg_filter_graph_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void zimg_filter_graph_free(zimg_filter_graph *ptr)
     * }
     */
    public static MemorySegment zimg_filter_graph_free$address() {
        return zimg_filter_graph_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void zimg_filter_graph_free(zimg_filter_graph *ptr)
     * }
     */
    public static void zimg_filter_graph_free(MemorySegment ptr) {
        var mh$ = zimg_filter_graph_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("zimg_filter_graph_free", ptr);
            }
            mh$.invokeExact(ptr);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class zimg_filter_graph_get_tmp_size {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            zimg_h.C_INT,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("zimg_filter_graph_get_tmp_size");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_get_tmp_size(const zimg_filter_graph *ptr, size_t *out)
     * }
     */
    public static FunctionDescriptor zimg_filter_graph_get_tmp_size$descriptor() {
        return zimg_filter_graph_get_tmp_size.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_get_tmp_size(const zimg_filter_graph *ptr, size_t *out)
     * }
     */
    public static MethodHandle zimg_filter_graph_get_tmp_size$handle() {
        return zimg_filter_graph_get_tmp_size.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_get_tmp_size(const zimg_filter_graph *ptr, size_t *out)
     * }
     */
    public static MemorySegment zimg_filter_graph_get_tmp_size$address() {
        return zimg_filter_graph_get_tmp_size.ADDR;
    }

    /**
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_get_tmp_size(const zimg_filter_graph *ptr, size_t *out)
     * }
     */
    public static int zimg_filter_graph_get_tmp_size(MemorySegment ptr, MemorySegment out) {
        var mh$ = zimg_filter_graph_get_tmp_size.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("zimg_filter_graph_get_tmp_size", ptr, out);
            }
            return (int)mh$.invokeExact(ptr, out);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class zimg_filter_graph_process {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            zimg_h.C_INT,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("zimg_filter_graph_process");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_process(const zimg_filter_graph *ptr, const zimg_image_buffer_const *src, const zimg_image_buffer *dst, void *tmp, zimg_filter_graph_callback unpack_cb, void *unpack_user, zimg_filter_graph_callback pack_cb, void *pack_user)
     * }
     */
    public static FunctionDescriptor zimg_filter_graph_process$descriptor() {
        return zimg_filter_graph_process.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_process(const zimg_filter_graph *ptr, const zimg_image_buffer_const *src, const zimg_image_buffer *dst, void *tmp, zimg_filter_graph_callback unpack_cb, void *unpack_user, zimg_filter_graph_callback pack_cb, void *pack_user)
     * }
     */
    public static MethodHandle zimg_filter_graph_process$handle() {
        return zimg_filter_graph_process.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_process(const zimg_filter_graph *ptr, const zimg_image_buffer_const *src, const zimg_image_buffer *dst, void *tmp, zimg_filter_graph_callback unpack_cb, void *unpack_user, zimg_filter_graph_callback pack_cb, void *pack_user)
     * }
     */
    public static MemorySegment zimg_filter_graph_process$address() {
        return zimg_filter_graph_process.ADDR;
    }

    /**
     * {@snippet lang=c :
     * zimg_error_code_e zimg_filter_graph_process(const zimg_filter_graph *ptr, const zimg_image_buffer_const *src, const zimg_image_buffer *dst, void *tmp, zimg_filter_graph_callback unpack_cb, void *unpack_user, zimg_filter_graph_callback pack_cb, void *pack_user)
     * }
     */
    public static int zimg_filter_graph_process(MemorySegment ptr, MemorySegment src, MemorySegment dst, MemorySegment tmp, MemorySegment unpack_cb, MemorySegment unpack_user, MemorySegment pack_cb, MemorySegment pack_user) {
        var mh$ = zimg_filter_graph_process.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("zimg_filter_graph_process", ptr, src, dst, tmp, unpack_cb, unpack_user, pack_cb, pack_user);
            }
            return (int)mh$.invokeExact(ptr, src, dst, tmp, unpack_cb, unpack_user, pack_cb, pack_user);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class zimg_image_format_default {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            zimg_h.C_POINTER,
            zimg_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("zimg_image_format_default");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void zimg_image_format_default(zimg_image_format *ptr, unsigned int version)
     * }
     */
    public static FunctionDescriptor zimg_image_format_default$descriptor() {
        return zimg_image_format_default.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void zimg_image_format_default(zimg_image_format *ptr, unsigned int version)
     * }
     */
    public static MethodHandle zimg_image_format_default$handle() {
        return zimg_image_format_default.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void zimg_image_format_default(zimg_image_format *ptr, unsigned int version)
     * }
     */
    public static MemorySegment zimg_image_format_default$address() {
        return zimg_image_format_default.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void zimg_image_format_default(zimg_image_format *ptr, unsigned int version)
     * }
     */
    public static void zimg_image_format_default(MemorySegment ptr, int version) {
        var mh$ = zimg_image_format_default.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("zimg_image_format_default", ptr, version);
            }
            mh$.invokeExact(ptr, version);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class zimg_graph_builder_params_default {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            zimg_h.C_POINTER,
            zimg_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("zimg_graph_builder_params_default");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void zimg_graph_builder_params_default(zimg_graph_builder_params *ptr, unsigned int version)
     * }
     */
    public static FunctionDescriptor zimg_graph_builder_params_default$descriptor() {
        return zimg_graph_builder_params_default.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void zimg_graph_builder_params_default(zimg_graph_builder_params *ptr, unsigned int version)
     * }
     */
    public static MethodHandle zimg_graph_builder_params_default$handle() {
        return zimg_graph_builder_params_default.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void zimg_graph_builder_params_default(zimg_graph_builder_params *ptr, unsigned int version)
     * }
     */
    public static MemorySegment zimg_graph_builder_params_default$address() {
        return zimg_graph_builder_params_default.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void zimg_graph_builder_params_default(zimg_graph_builder_params *ptr, unsigned int version)
     * }
     */
    public static void zimg_graph_builder_params_default(MemorySegment ptr, int version) {
        var mh$ = zimg_graph_builder_params_default.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("zimg_graph_builder_params_default", ptr, version);
            }
            mh$.invokeExact(ptr, version);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class zimg_filter_graph_build {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER,
            zimg_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("zimg_filter_graph_build");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * zimg_filter_graph *zimg_filter_graph_build(const zimg_image_format *src_format, const zimg_image_format *dst_format, const zimg_graph_builder_params *params)
     * }
     */
    public static FunctionDescriptor zimg_filter_graph_build$descriptor() {
        return zimg_filter_graph_build.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * zimg_filter_graph *zimg_filter_graph_build(const zimg_image_format *src_format, const zimg_image_format *dst_format, const zimg_graph_builder_params *params)
     * }
     */
    public static MethodHandle zimg_filter_graph_build$handle() {
        return zimg_filter_graph_build.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * zimg_filter_graph *zimg_filter_graph_build(const zimg_image_format *src_format, const zimg_image_format *dst_format, const zimg_graph_builder_params *params)
     * }
     */
    public static MemorySegment zimg_filter_graph_build$address() {
        return zimg_filter_graph_build.ADDR;
    }

    /**
     * {@snippet lang=c :
     * zimg_filter_graph *zimg_filter_graph_build(const zimg_image_format *src_format, const zimg_image_format *dst_format, const zimg_graph_builder_params *params)
     * }
     */
    public static MemorySegment zimg_filter_graph_build(MemorySegment src_format, MemorySegment dst_format, MemorySegment params) {
        var mh$ = zimg_filter_graph_build.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("zimg_filter_graph_build", src_format, dst_format, params);
            }
            return (MemorySegment)mh$.invokeExact(src_format, dst_format, params);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int ZIMG_API_VERSION = (int)516L;
    /**
     * {@snippet lang=c :
     * #define ZIMG_API_VERSION 516
     * }
     */
    public static int ZIMG_API_VERSION() {
        return ZIMG_API_VERSION;
    }
    private static final int ZIMG_BUFFER_MAX = (int)4294967295L;
    /**
     * {@snippet lang=c :
     * #define ZIMG_BUFFER_MAX 4294967295
     * }
     */
    public static int ZIMG_BUFFER_MAX() {
        return ZIMG_BUFFER_MAX;
    }
}

