// Generated by jextract

package com.loadingbyte.cinecred.natives.harfbuzz;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$1 {

    static final FunctionDescriptor hb_reference_table_func_t$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle hb_reference_table_func_t$MH = RuntimeHelper.downcallHandle(
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$1.hb_reference_table_func_t$FUNC, false
    );
    static final FunctionDescriptor hb_face_create_for_tables$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle hb_face_create_for_tables$MH = RuntimeHelper.downcallHandle(
        hb_h.LIBRARIES, "hb_face_create_for_tables",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$1.hb_face_create_for_tables$FUNC, false
    );
    static final FunctionDescriptor hb_face_destroy$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle hb_face_destroy$MH = RuntimeHelper.downcallHandle(
        hb_h.LIBRARIES, "hb_face_destroy",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1.hb_face_destroy$FUNC, false
    );
    static final FunctionDescriptor hb_font_create$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle hb_font_create$MH = RuntimeHelper.downcallHandle(
        hb_h.LIBRARIES, "hb_font_create",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$1.hb_font_create$FUNC, false
    );
    static final FunctionDescriptor hb_font_destroy$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle hb_font_destroy$MH = RuntimeHelper.downcallHandle(
        hb_h.LIBRARIES, "hb_font_destroy",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$1.hb_font_destroy$FUNC, false
    );
    static final FunctionDescriptor hb_font_set_scale$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_INT,
        C_INT
    );
    static final MethodHandle hb_font_set_scale$MH = RuntimeHelper.downcallHandle(
        hb_h.LIBRARIES, "hb_font_set_scale",
        "(Ljdk/incubator/foreign/MemoryAddress;II)V",
        constants$1.hb_font_set_scale$FUNC, false
    );
}


