// Generated by jextract

package com.loadingbyte.cinecred.natives.harfbuzz;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public class hb_feature_t {

    static final MemoryLayout $struct$LAYOUT = MemoryLayout.structLayout(
        C_INT.withName("tag"),
        C_INT.withName("value"),
        C_INT.withName("start"),
        C_INT.withName("end")
    ).withName("hb_feature_t");
    public static MemoryLayout $LAYOUT() {
        return hb_feature_t.$struct$LAYOUT;
    }
    static final VarHandle tag$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("tag"));
    public static VarHandle tag$VH() {
        return hb_feature_t.tag$VH;
    }
    public static int tag$get(MemorySegment seg) {
        return (int)hb_feature_t.tag$VH.get(seg);
    }
    public static void tag$set( MemorySegment seg, int x) {
        hb_feature_t.tag$VH.set(seg, x);
    }
    public static int tag$get(MemorySegment seg, long index) {
        return (int)hb_feature_t.tag$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void tag$set(MemorySegment seg, long index, int x) {
        hb_feature_t.tag$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle value$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("value"));
    public static VarHandle value$VH() {
        return hb_feature_t.value$VH;
    }
    public static int value$get(MemorySegment seg) {
        return (int)hb_feature_t.value$VH.get(seg);
    }
    public static void value$set( MemorySegment seg, int x) {
        hb_feature_t.value$VH.set(seg, x);
    }
    public static int value$get(MemorySegment seg, long index) {
        return (int)hb_feature_t.value$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void value$set(MemorySegment seg, long index, int x) {
        hb_feature_t.value$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle start$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("start"));
    public static VarHandle start$VH() {
        return hb_feature_t.start$VH;
    }
    public static int start$get(MemorySegment seg) {
        return (int)hb_feature_t.start$VH.get(seg);
    }
    public static void start$set( MemorySegment seg, int x) {
        hb_feature_t.start$VH.set(seg, x);
    }
    public static int start$get(MemorySegment seg, long index) {
        return (int)hb_feature_t.start$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void start$set(MemorySegment seg, long index, int x) {
        hb_feature_t.start$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle end$VH = $struct$LAYOUT.varHandle(int.class, MemoryLayout.PathElement.groupElement("end"));
    public static VarHandle end$VH() {
        return hb_feature_t.end$VH;
    }
    public static int end$get(MemorySegment seg) {
        return (int)hb_feature_t.end$VH.get(seg);
    }
    public static void end$set( MemorySegment seg, int x) {
        hb_feature_t.end$VH.set(seg, x);
    }
    public static int end$get(MemorySegment seg, long index) {
        return (int)hb_feature_t.end$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void end$set(MemorySegment seg, long index, int x) {
        hb_feature_t.end$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.ofScope(scope)); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.ofScope(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


