// Generated by jextract

package com.loadingbyte.cinecred.natives.harfbuzz;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct hb_glyph_extents_t {
 *     hb_position_t x_bearing;
 *     hb_position_t y_bearing;
 *     hb_position_t width;
 *     hb_position_t height;
 * }
 * }
 */
public class hb_glyph_extents_t {

    hb_glyph_extents_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        hb_h.C_INT.withName("x_bearing"),
        hb_h.C_INT.withName("y_bearing"),
        hb_h.C_INT.withName("width"),
        hb_h.C_INT.withName("height")
    ).withName("hb_glyph_extents_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt x_bearing$LAYOUT = (OfInt)$LAYOUT.select(groupElement("x_bearing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hb_position_t x_bearing
     * }
     */
    public static final OfInt x_bearing$layout() {
        return x_bearing$LAYOUT;
    }

    private static final long x_bearing$OFFSET = $LAYOUT.byteOffset(groupElement("x_bearing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hb_position_t x_bearing
     * }
     */
    public static final long x_bearing$offset() {
        return x_bearing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hb_position_t x_bearing
     * }
     */
    public static int x_bearing(MemorySegment struct) {
        return struct.get(x_bearing$LAYOUT, x_bearing$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hb_position_t x_bearing
     * }
     */
    public static void x_bearing(MemorySegment struct, int fieldValue) {
        struct.set(x_bearing$LAYOUT, x_bearing$OFFSET, fieldValue);
    }

    private static final OfInt y_bearing$LAYOUT = (OfInt)$LAYOUT.select(groupElement("y_bearing"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hb_position_t y_bearing
     * }
     */
    public static final OfInt y_bearing$layout() {
        return y_bearing$LAYOUT;
    }

    private static final long y_bearing$OFFSET = $LAYOUT.byteOffset(groupElement("y_bearing"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hb_position_t y_bearing
     * }
     */
    public static final long y_bearing$offset() {
        return y_bearing$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hb_position_t y_bearing
     * }
     */
    public static int y_bearing(MemorySegment struct) {
        return struct.get(y_bearing$LAYOUT, y_bearing$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hb_position_t y_bearing
     * }
     */
    public static void y_bearing(MemorySegment struct, int fieldValue) {
        struct.set(y_bearing$LAYOUT, y_bearing$OFFSET, fieldValue);
    }

    private static final OfInt width$LAYOUT = (OfInt)$LAYOUT.select(groupElement("width"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hb_position_t width
     * }
     */
    public static final OfInt width$layout() {
        return width$LAYOUT;
    }

    private static final long width$OFFSET = $LAYOUT.byteOffset(groupElement("width"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hb_position_t width
     * }
     */
    public static final long width$offset() {
        return width$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hb_position_t width
     * }
     */
    public static int width(MemorySegment struct) {
        return struct.get(width$LAYOUT, width$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hb_position_t width
     * }
     */
    public static void width(MemorySegment struct, int fieldValue) {
        struct.set(width$LAYOUT, width$OFFSET, fieldValue);
    }

    private static final OfInt height$LAYOUT = (OfInt)$LAYOUT.select(groupElement("height"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hb_position_t height
     * }
     */
    public static final OfInt height$layout() {
        return height$LAYOUT;
    }

    private static final long height$OFFSET = $LAYOUT.byteOffset(groupElement("height"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hb_position_t height
     * }
     */
    public static final long height$offset() {
        return height$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hb_position_t height
     * }
     */
    public static int height(MemorySegment struct) {
        return struct.get(height$LAYOUT, height$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hb_position_t height
     * }
     */
    public static void height(MemorySegment struct, int fieldValue) {
        struct.set(height$LAYOUT, height$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

