// Generated by jextract

package com.loadingbyte.cinecred.natives.harfbuzz;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct hb_ot_name_entry_t {
 *     hb_ot_name_id_t name_id;
 *     hb_var_int_t var;
 *     hb_language_t language;
 * }
 * }
 */
public class hb_ot_name_entry_t {

    hb_ot_name_entry_t() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        hb_h.C_INT.withName("name_id"),
        _hb_var_int_t.layout().withName("var"),
        hb_h.C_POINTER.withName("language")
    ).withName("hb_ot_name_entry_t");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt name_id$LAYOUT = (OfInt)$LAYOUT.select(groupElement("name_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hb_ot_name_id_t name_id
     * }
     */
    public static final OfInt name_id$layout() {
        return name_id$LAYOUT;
    }

    private static final long name_id$OFFSET = $LAYOUT.byteOffset(groupElement("name_id"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hb_ot_name_id_t name_id
     * }
     */
    public static final long name_id$offset() {
        return name_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hb_ot_name_id_t name_id
     * }
     */
    public static int name_id(MemorySegment struct) {
        return struct.get(name_id$LAYOUT, name_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hb_ot_name_id_t name_id
     * }
     */
    public static void name_id(MemorySegment struct, int fieldValue) {
        struct.set(name_id$LAYOUT, name_id$OFFSET, fieldValue);
    }

    private static final GroupLayout var_$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("var"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hb_var_int_t var
     * }
     */
    public static final GroupLayout var_$layout() {
        return var_$LAYOUT;
    }

    private static final long var_$OFFSET = $LAYOUT.byteOffset(groupElement("var"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hb_var_int_t var
     * }
     */
    public static final long var_$offset() {
        return var_$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hb_var_int_t var
     * }
     */
    public static MemorySegment var_(MemorySegment struct) {
        return struct.asSlice(var_$OFFSET, var_$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hb_var_int_t var
     * }
     */
    public static void var_(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, var_$OFFSET, var_$LAYOUT.byteSize());
    }

    private static final AddressLayout language$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("language"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hb_language_t language
     * }
     */
    public static final AddressLayout language$layout() {
        return language$LAYOUT;
    }

    private static final long language$OFFSET = $LAYOUT.byteOffset(groupElement("language"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hb_language_t language
     * }
     */
    public static final long language$offset() {
        return language$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hb_language_t language
     * }
     */
    public static MemorySegment language(MemorySegment struct) {
        return struct.get(language$LAYOUT, language$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hb_language_t language
     * }
     */
    public static void language(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(language$LAYOUT, language$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

