// Generated by jextract

package com.loadingbyte.cinecred.natives.skcms;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct skcms_CICP {
 *     uint8_t color_primaries;
 *     uint8_t transfer_characteristics;
 *     uint8_t matrix_coefficients;
 *     uint8_t video_full_range_flag;
 * }
 * }
 */
public class skcms_CICP {

    skcms_CICP() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        skcms_h.C_CHAR.withName("color_primaries"),
        skcms_h.C_CHAR.withName("transfer_characteristics"),
        skcms_h.C_CHAR.withName("matrix_coefficients"),
        skcms_h.C_CHAR.withName("video_full_range_flag")
    ).withName("skcms_CICP");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfByte color_primaries$LAYOUT = (OfByte)$LAYOUT.select(groupElement("color_primaries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t color_primaries
     * }
     */
    public static final OfByte color_primaries$layout() {
        return color_primaries$LAYOUT;
    }

    private static final long color_primaries$OFFSET = $LAYOUT.byteOffset(groupElement("color_primaries"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t color_primaries
     * }
     */
    public static final long color_primaries$offset() {
        return color_primaries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t color_primaries
     * }
     */
    public static byte color_primaries(MemorySegment struct) {
        return struct.get(color_primaries$LAYOUT, color_primaries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t color_primaries
     * }
     */
    public static void color_primaries(MemorySegment struct, byte fieldValue) {
        struct.set(color_primaries$LAYOUT, color_primaries$OFFSET, fieldValue);
    }

    private static final OfByte transfer_characteristics$LAYOUT = (OfByte)$LAYOUT.select(groupElement("transfer_characteristics"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t transfer_characteristics
     * }
     */
    public static final OfByte transfer_characteristics$layout() {
        return transfer_characteristics$LAYOUT;
    }

    private static final long transfer_characteristics$OFFSET = $LAYOUT.byteOffset(groupElement("transfer_characteristics"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t transfer_characteristics
     * }
     */
    public static final long transfer_characteristics$offset() {
        return transfer_characteristics$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t transfer_characteristics
     * }
     */
    public static byte transfer_characteristics(MemorySegment struct) {
        return struct.get(transfer_characteristics$LAYOUT, transfer_characteristics$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t transfer_characteristics
     * }
     */
    public static void transfer_characteristics(MemorySegment struct, byte fieldValue) {
        struct.set(transfer_characteristics$LAYOUT, transfer_characteristics$OFFSET, fieldValue);
    }

    private static final OfByte matrix_coefficients$LAYOUT = (OfByte)$LAYOUT.select(groupElement("matrix_coefficients"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t matrix_coefficients
     * }
     */
    public static final OfByte matrix_coefficients$layout() {
        return matrix_coefficients$LAYOUT;
    }

    private static final long matrix_coefficients$OFFSET = $LAYOUT.byteOffset(groupElement("matrix_coefficients"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t matrix_coefficients
     * }
     */
    public static final long matrix_coefficients$offset() {
        return matrix_coefficients$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t matrix_coefficients
     * }
     */
    public static byte matrix_coefficients(MemorySegment struct) {
        return struct.get(matrix_coefficients$LAYOUT, matrix_coefficients$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t matrix_coefficients
     * }
     */
    public static void matrix_coefficients(MemorySegment struct, byte fieldValue) {
        struct.set(matrix_coefficients$LAYOUT, matrix_coefficients$OFFSET, fieldValue);
    }

    private static final OfByte video_full_range_flag$LAYOUT = (OfByte)$LAYOUT.select(groupElement("video_full_range_flag"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t video_full_range_flag
     * }
     */
    public static final OfByte video_full_range_flag$layout() {
        return video_full_range_flag$LAYOUT;
    }

    private static final long video_full_range_flag$OFFSET = $LAYOUT.byteOffset(groupElement("video_full_range_flag"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t video_full_range_flag
     * }
     */
    public static final long video_full_range_flag$offset() {
        return video_full_range_flag$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t video_full_range_flag
     * }
     */
    public static byte video_full_range_flag(MemorySegment struct) {
        return struct.get(video_full_range_flag$LAYOUT, video_full_range_flag$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t video_full_range_flag
     * }
     */
    public static void video_full_range_flag(MemorySegment struct, byte fieldValue) {
        struct.set(video_full_range_flag$LAYOUT, video_full_range_flag$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

